### ISSUE TITLE
Add Consistency+

### ISSUE THREAD

**Issue by Siuolplex** [frikinjay/packzero#3]
I love shameless self plugs! https://modrinth.com/mod/consistencyplus (If theres a problem I get a fix)

**Comment by Siuolplex** [comment]
Also maybe add Soul Ice https://modrinth.com/mod/soulice it would be incredibly cool of you

**Comment by frikinjay** [comment]
Added in 2.0.9

**Comment by Siuolplex** [comment]
Woooo
