### ISSUE TITLE
Recipe Conflicts/Issues - MI, Tech Reborn, and Create

### ISSUE THREAD

**Issue by zcctt1** [frikinjay/packzero#9]
Invar and invar dust do not have recipes. (see screenshot)

on my server trying to craft invar, the only method showing is using the mixer from Create, and it is only for one type of Invar from Tech Reborn. This still did not craft the invar. The invar from MI is uncraftable. it only seems to be findable in dudgeon chests and not craftable.

iron ore dust is also uncraftable with a hammer and will not grind in the MI grinder. It seems like I can craft some dusts and not others. (see screenshots)

![image](https://user-images.githubusercontent.com/59290328/208333453-4a8b6c53-aeb3-4d44-bc47-ccdbca7c720a.png)

![image](https://user-images.githubusercontent.com/59290328/208333496-2fca0e54-d8a0-4976-be8e-f15b4cdacefc.png)

![image](https://user-images.githubusercontent.com/59290328/208333921-e247badd-9c86-4475-a448-8635603c4fb2.png)

**Comment by frikinjay** [comment]
I will look into this

**Comment by zcctt1** [comment]
There is also an issue with the steel ingots from modern industrialization and tech reborn. They can only be crafted in a mixer from create but the recipe does not work.

**Comment by frikinjay** [comment]
Fixed in 2.0.21
